# Generated by Django 4.0.1 on 2022-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='internal',
            field=models.BooleanField(default=False, verbose_name='Internal Note?'),
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=1, verbose_name='Note Priority'),
        ),
    ]
