# Generated by Django 4.0.1 on 2022-01-31 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('social_media', models.CharField(max_length=255, verbose_name='Social Media')),
                ('major', models.CharField(max_length=255, verbose_name='Major')),
                ('education', models.JSONField(verbose_name='Education')),
                ('ielts', models.CharField(max_length=255, verbose_name='IELTS')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Student Data',
                'verbose_name_plural': 'Student Data',
                'ordering': ['id'],
            },
        ),
    ]
