# Generated by Django 4.0.1 on 2022-02-01 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('social_media', models.CharField(max_length=255, verbose_name='Social Media')),
                ('major', models.CharField(max_length=255, verbose_name='Major')),
                ('education', models.JSONField(verbose_name='Education')),
                ('english_proficiency', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('no-test', 'Wish to get enrolled without any test'), ('moi', 'Wish to get enrolled with Medium Of Instruction'), ('plan-to', 'Wish to take IELTS')], default='ielts', max_length=15, verbose_name='English Proficiency')),
                ('english_proficiency_score', models.CharField(blank=True, max_length=255, null=True, verbose_name='Score')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Student Data',
                'verbose_name_plural': 'Student Data',
                'ordering': ['id'],
            },
        ),
    ]
