# Generated by Django 4.0.1 on 2022-02-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
