# Generated by Django 4.0.1 on 2022-02-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_alter_studentdata_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Social Media'),
        ),
    ]
