# Generated by Django 4.0.1 on 2022-02-21 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_data', '0004_alter_studentdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudentData',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('social_media', models.CharField(blank=True, max_length=255, null=True, verbose_name='Social Media')),
                ('major', models.CharField(max_length=255, verbose_name='Major')),
                ('education', models.JSONField(verbose_name='Education')),
                ('english_proficiency', models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('duolingo', 'Duolingo'), ('no-test', 'Wish to get enrolled without any test'), ('moi', 'Wish to get enrolled with Medium Of Instruction'), ('plan-to', 'Wish to take IELTS')], default='ielts', max_length=15, verbose_name='English Proficiency')),
                ('english_proficiency_score', models.CharField(blank=True, max_length=255, null=True, verbose_name='Score')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('dr_rashids_notes', models.TextField(blank=True, null=True, verbose_name="Dr. Rashid's Notes")),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Package Sent'), (2, 'Converted'), (3, 'Follow-up'), (4, 'Muted')], default=0, verbose_name='Status')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Rating')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Student Data',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
