# Generated by Django 4.0.1 on 2022-03-13 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_data', '0005_historicalstudentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_creation', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Account Creation')),
                ('file_opening', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='File Opening')),
                ('docu_submission', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Submission of Documents')),
                ('application_submission', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Submission of Application')),
                ('i20_reception', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Receipt of I-20')),
                ('sevis_payment', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='SEVIS Payment')),
                ('ds160_submission', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Submission of DS-160')),
                ('visa_fee', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Visa Processing Fee Payment')),
                ('visa_interview', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Visa Interview Preparation')),
                ('visa_collection', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Visa Collection')),
                ('pre_dept_session', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Pre-departure Session')),
                ('welcoming_in_us', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Welcoming in the USA')),
                ('student_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='student_data.studentdata')),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudentProgress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_creation', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Account Creation')),
                ('file_opening', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='File Opening')),
                ('docu_submission', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Submission of Documents')),
                ('application_submission', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Submission of Application')),
                ('i20_reception', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Receipt of I-20')),
                ('sevis_payment', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='SEVIS Payment')),
                ('ds160_submission', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Submission of DS-160')),
                ('visa_fee', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Visa Processing Fee Payment')),
                ('visa_interview', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Visa Interview Preparation')),
                ('visa_collection', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Visa Collection')),
                ('pre_dept_session', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Pre-departure Session')),
                ('welcoming_in_us', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Incomplete'), (3, 'Completed')], default=1, verbose_name='Welcoming in the USA')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student_data', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student_data.studentdata')),
            ],
            options={
                'verbose_name': 'historical Student Progress',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
