# Generated by Django 4.0.1 on 2022-03-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0007_historicalstudentdata_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentdata',
            name='middle_initials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Initials'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='middle_initials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Initials'),
        ),
    ]
