# Generated by Django 4.0.1 on 2022-02-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_alter_studentdata_email_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Consultant'), (3, 'Manager'), (4, 'Admin'), (5, 'SuperAdmin')], default=1, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='student_data.studentdata'),
        ),
    ]
