# Generated by Django 4.0.1 on 2022-02-15 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_alter_studentdata_email_and_more'),
        ('accounts', '0002_accounts_account_type_accounts_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Visitor'), (2, 'Client'), (3, 'Consultant'), (4, 'Manager'), (5, 'Admin'), (6, 'SuperAdmin')], default=1, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='student_data.studentdata'),
        ),
    ]
