# Generated by Django 4.0.1 on 2022-02-27 10:14

import apps.accounts.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicalaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profiles/avatar.png', null=True, upload_to=apps.accounts.models.upload_to_path),
        ),
        migrations.AddField(
            model_name='historicalaccounts',
            name='profile_pic',
            field=models.TextField(blank=True, default='profiles/avatar.png', max_length=100, null=True),
        ),
    ]
