# Generated by Django 4.0.1 on 2022-05-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='code',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
