# Generated by Django 4.0.1 on 2022-05-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_submission', '0002_documentcategory_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['code'], 'verbose_name': 'Document Category', 'verbose_name_plural': 'Document Categories'},
        ),
    ]
